"""add preferences

Revision ID: 78604dcd14d1
Revises: 3dded2618d49
Create Date: 2026-02-23 23:48:30.881403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78604dcd14d1'
down_revision = '3dded2618d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notif_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feed_sorting', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accent_color')
        batch_op.drop_column('feed_sorting')
        batch_op.drop_column('email_notif_enabled')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('profile_visibility')
        batch_op.drop_column('msg_preference')

    # ### end Alembic commands ###
